# Generated by Django 3.2.19 on 2023-05-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='matricula',
            field=models.IntegerField(unique=True, verbose_name=''),
        ),
    ]
