# Generated by Django 3.2.19 on 2023-05-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_professor_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='matricula',
            field=models.IntegerField(unique=True),
        ),
    ]
