# Generated by Django 3.2.19 on 2023-05-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230520_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='disciplinas',
        ),
    ]
